version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Base image with Docker CLI

    steps:
      - setup_remote_docker
      - run:
          name: Run Docker image with NET_ADMIN
          command: |
            docker pull alimoe88/alyo
            docker run --rm --cap-add=NET_ADMIN --device=/dev/net/tun alimoe88/alyo
